[auth]
cookie_name = "viz_builder_auth"
cookie_key = "REPLACE_WITH_32+_CHAR_RANDOM_SECRET"
cookie_expiry_days = 7
preauthorized = ["shaswotjoshi@gmail.com", "alex@purposely.ai"]

[credentials]
[credentials.usernames]
    [credentials.usernames.shaswot]
    name = "shaswot"
    password = "$2b$12$EI9EH7BXvc.UsWFhMYHC..57tC8qV6KmNby0pWp1ojZFunxhvzU6."

    [credentials.usernames.alex]
    name = "Alex"
    password = "$2b$12$EI9EH7BXvc.UsWFhMYHC..57tC8qV6KmNby0pWp1ojZFunxhvzU6."

    [credentials.usernames.juliana]
    name = "Juliana"
    password = "$2b$12$ABnEOtPfKFKxzj548xZhweROlxjkXRoH9xdB/pbiAreeKt9fhzK86"
